gkaguirrelab/transparentTrack

code/correctPupilPerimeterVideo.m
code/importControlFile.m
code/makeControlFile.m
code/makePreliminaryControlFile.m
code/parseInstructionParams.m

Control file is now saved only in cvs format. Appropriate functions have been added to import the file to matlab appropriately

ControlFileDEV

---

code/bayesFitPupilPerimeter.m

function now outputs the correct struct for pupil tracking data.

added output for bayesFitPupilPerimeter

---

code/trackGlint.m

Comment clean up

---

code/processVideos/processVideoPipeline.m

Skip stage accepts cell array containing the names of the stages that
the user does not want to perform.
Note that if you skip a stage required for a subsequent step (and that
stage was never performed before) the processing pipeline will likely
return an error.

Added skipStage optional parameter

---

code/processVideos/bayesFitPupilPerimeter.m
code/processVideos/fitIrisCircleAndMask.m
code/processVideos/makePupilFitVideo.m
code/processVideos/processVideoPipeline.m

Variable and file name harmonization

---

code/processVideos/processVideoPipeline.m

Also fixed the count for the attempts in the try catch loop to start
from 1 instead then 0.
Waiting for @gkaguirre ’s seal of approval before merging.

Condensed the processPipeline in a compact for loop.

---

code/processVideos/makePupilFitVideo.m
code/processVideos/testParams.m

Merge clean up

---

code/processVideos/convertIntrisicToWorldCoordinates.m
code/processVideos/findGlint.m
code/processVideos/fitPupilPerimeter.m

- Pupil data is automatically converted from intrinsic to world coordinates before saving.
- Meta field “coordinatesSystem” added to pupil and glint files.
- Documentation about intrinsic and world coordinates added.

CoordConversion DEV

---

code/processVideos/fitPupilPerimeter.m
code/processVideos/loadControlFile.m
code/processVideos/makeControlFile.m
code/processVideos/makeFitVideo.m

- makeControlFile now saves the analysis parameter as comment entries in the resulting control file
- now handles the case in which no instructions are needed in the control file
- updated the filed 'tbtbRepoName' to be 'transparentTrack' in those routines that execute parpool jobs

Control file param dev

---

code/demoAndValidate/DEMO_distanceAndCOP.m
code/processVideos/estimateSceneGeometry.m
code/processVideos/geometryAndProjection/calcEyeCenterOfRotation.m
code/processVideos/geometryAndProjection/pupilProjection_fwd.m
code/processVideos/geometryAndProjection/pupilProjection_inv.m

- Cleaned up parameter names
- Sped up routines by removing unnecessary environmental parameter calls within utility functions
- Fixed up comments throughout

Geom clean up

---

code/processVideos/fitPupilPerimeter.m
code/processVideos/makeControlFile.m
code/processVideos/quadfitExtension/constrainedEllipseFit.m
code/processVideos/smoothPupilArea.m

If the ellipse fitting routine detects a possible local minimum result, it then engages in a more time consuming global search

Global min ellipse fit

---

code/demoAndValidate/TEST_deriveSceneGeometryFromOrthogonalProjectionCase.m
code/processVideos/applyControlFile.m
code/processVideos/findPupilPerimeter.m
code/processVideos/fitPupilPerimeter.m
code/processVideos/makeControlFile.m
code/processVideos/makeFitVideo.m
code/processVideos/smoothPupilArea.m

Compact format for perimeter data storage. Also lends itself to use as a sliced cell array in par for loops.

Perimeter compress dev

---

code/demoAndValidate/TEST_simulatedSceneGeometryConstraint.m
code/processVideos/estimateSceneGeometry.m
code/processVideos/findPupilPerimeter.m
code/processVideos/utilityFunctions/pupilProjection_fwd.m
code/processVideos/utilityFunctions/pupilProjection_inv.m

Exhaustive effort by Giulia to track down and squash every last imperfection in our ability to create a simulated pseudoPerspective projection of the eye and to then model it with pixel accuracy.

Perspective dev

---

code/demoAndTest/DEMO_eyePoses.m
code/demoAndTest/TEST_EntrancePupilShape.m
code/demoAndTest/TEST_estimateSceneGeometry.m
code/processVideos/eyeModel/modelEyeParameters.m
code/processVideos/eyeModel/pupilProjection_fwd.m
code/processVideos/eyeModel/rayTraceCenteredSphericalSurfaces.m
code/processVideos/runVideoPipeline.m
code/processVideos/stages/applyControlFile.m
code/processVideos/stages/makeEyeModelVideo.m
code/processVideos/utilityFunctions/parseControlInstructions.m

- Can now pass a custom input sceneGeometry filename to the video pipeline, allowing the video from one acquisition to be analyzed with the sceneGeometry file from a different acquisition. Not yet tested.
- The control file can now include specification of the parameters of an ellipse in transparent format. Not yet tested.
- Various comment improvements and variable name tweaks

Small updates

---

code/processVideos/modelEye/createSceneGeometry.m

Added option to save sceneGeometry

---

code/processVideos/runVideoPipeline.m
code/processVideos/stages/makeEyeModelVideo.m
code/processVideos/stages/makeFitVideo.m

The fit video now optionally super-imposes a transparent plot of the model eye on the fit video

Alpha eye model

---

code/processVideos/modelEye/addContactLens.m
code/processVideos/modelEye/addSpectacleLens.m
code/processVideos/modelEye/createSceneGeometry.m
code/processVideos/modelEye/modelEyeParameters.m
code/processVideos/modelEye/pupilProjection_fwd.m

Fixed an error in how the radii of the anterior chamber were calculated. The iris is now an appropriate size.

Cornea radii fix

---

code/ellipseFit/eyePoseEllipseFit.m
code/modelEye/addContactLens.m
code/modelEye/createSceneGeometry.m
code/modelEye/modelEyeParameters.m
code/modelEye/pupilProjection_fwd.m
code/modelEye/pupilProjection_inv.m
code/modelEye/rayTraceCenteredSphericalSurfaces.m
code/stages/estimateSceneParams.m
code/stages/fitPupilPerimeter.m
code/stages/makeEyeModelVideo.m
code/stages/makeFitVideo.m
code/stages/smoothPupilRadius.m

Various bug fixes and improvements to the estimation of scene geometry parameters and the application of empirical Bayes smoothing to the pupil radius in time.

Bayes smooth fix

---

code/modelEye/createSceneGeometry.m
code/stages/estimateSceneParams.m

Had bigger plans; realized that I need to go in a different direction. Look to the next pull request.

Tiny edits

---

code/modelEye/pupilProjection_fwd.m
code/modelEye/pupilProjection_inv.m
code/stages/estimateSceneParams.m

estimateSceneParams now allows for a search across camera Z rotation

Search over camera rotation

---

stages/estimateSceneParams.m

Silencing a warning

---

stages/estimateSceneParams.m

Added functionality to estimate scene geometry so that a request for zero searches can be passed. This results in saving the default scene geometry file. Also, the diagnostic plot now includes the ellipseArray used to  estimate the parameters.

Scene geom diagnostic tools

---

stages/deinterlaceVideo.m
stages/makeTimebase.m

Tested the functions 

---

stages/estimateSceneParams.m

Updates to make use of the updates to the gkaModelEye repo

New inverse

---

stages/estimateSceneParams.m
stages/fitPupilPerimeter.m
stages/smoothPupilRadius.m
utilities/estimateSceneParamsGUI.m

Compatibility with updates to gkaModelEye

Sync compile dev

---

stages/estimateSceneParams.m
stages/fitPupilPerimeter.m
stages/smoothPupilRadius.m
stages/syncSceneGeometry.m
utilities/depthFromIrisDiameter.m

Function calls to gkaModelEye updated for new function names

---

estimateSceneParams/+selectFrames/shape.m
estimateSceneParams/@sceneObj/saveRelCameraPos.m
estimateSceneParams/@sceneObj/saveRelCameraPosPlot.m
estimateSceneParams/@sceneObj/sceneObj.m
estimateSceneParams/estimateSceneParams.m
stages/fitPupilPerimeter.m
stages/makeFitVideo.m
stages/smoothPupilRadius.m

- estimateSceneGeometry now saves a plot of the initial and adjusted relative camera position
- the relativeCameraPosition and pupilData structures now include the field "currentField" that identifies the most recently produced analysis field.

Improved handling of relative camera position; pupilData struct update
